@startuml completeClassDiagramFinale
package controller {
    class HomeController{
        - search_button_clicked()
        - validate_date_range()
        - update_branch_list(repo_name : String)
        - new_repo_button_clicked()
        - delete_repo_button_clicked()
        - load_csv_file()
        - open_file_dialog()
        - clone_repo()
    }
    class TraceVisualizerController{
        + from_args(frameworks : string, from_date : datetime, to_date : datetime, repo_path : string, searched_path : string, searched_branch : string, searched_author : string)
        + from_file(file_path : Stirng)
        + show_comit_change(item : QtCore.Qt.ItemDataRole.UserRole)
        + set_view_data(log_instructions : log_instruction[])
        + filter_logs(filter : String)
        + highlight_graph_element(item : String)
        - set_strategy_collector(strategy : String) : LogInstructionCollectorsStrategy
        - set_strategy_generator_file(strategy : String) : LogInstructionFileGeneratorsStrategy
        - save_data()
        - naviguate_to_home()
    }

}

package model {

    class LogInstructionDiffGenerator{
        + getCommitChanges(commits : List<Commit>) : List<Modification>
    }
    class ReposManager{
        + get_repos(main_repo_path : String)
        + git_pull(repo_path:String)
        + delete_repo(repo_path:String)
        + getBranches(repo_path : String)
        + clone_repo(repo_url:String, repo_path:String)
    }
    package GraphBuilders{
        
        class GraphBuilder{
            + build_graph(path_to_file : String) : QGraphicsView
        }
    }
    package LogInstructionCollectors{
        interface LogInstructionCollector{
            + getLogInstructions():LogInstruction[]
        }
        class Log4JCollector{
            + getLogInstructions():LogInstruction[]
        }
        class Log4PCollector{
            + getLogInstructions():LogInstruction[]
        }

        class LogInstruction{
            - intruction : String
        }
        class Modification{
            - type : String
            - commit : Commit
        }
    }

    package LogInstructionFileGenerators{
        interface LogInstructionFileGenerator{
            + createFile(logInstructions : List<LogInstruction>) : String
        }

        class CsvFileGenerator implements LogInstructionFileGenerator{
            + createFile(logInstructions : List<LogInstruction>) : String
        }

        class JsonFIleGenerator implements LogInstructionFileGenerator{
            + createFile(logInstructions : List<LogInstruction>) : String
        }
    }
}

package view {
    class CommitWindowView{
        - code_table : QTableWidget
    }

    class HomeView {
        - branches : QComboBox
        - repo_list : QComboBox
        - new_repo_button : QPushButton
        - delete_repo_button : QPushButton
        - searched_path : QLineEdit
        - searched_author : QLineEdit
        - slected_framework : QListWidget
        - from_date_label : QLabel
        - from_calendar : QCalendarWidget
        - to_date_label : QLabel
        - to_calendat : QCalendarWidget
        - search_button : QPushButton
        - new_repo : QLineEdit
        - select_folder_button : QPushButton
        - Clone_button : QPushButton
        + setRepos(repos : List<String>)
        + setBranches(branches : List<String>)
    }
    class TraceVisualizerView{
        - log_instructions_list : QListWidget
        - graphic : QGraphicsView
        + set_log_instructions(logInstructions : List<LogInstruction>)
        + set_graphic(graphic : QGraphicsView)
        + highlight_log(event : QtCore.Qt.Event, log_instructions_list : List<LogInstruction>)
        + get_instruction_for_index(index : int)
    }
}

HomeController "1" o-- "1" HomeView
HomeController ..> TraceVisualizerController

TraceVisualizerController "1" o-- "1" TraceVisualizerView
TraceVisualizerController ..> LogInstructionDiffGenerator
TraceVisualizerController "1" o-- "1" LogInstructionCollector
TraceVisualizerController "1" o-- "1" LogInstructionFileGenerator
TraceVisualizerController "1" o-- "1" CommitWindowView
TraceVisualizerController ..> GraphBuilder

HomeController ..> ReposManager


Log4JCollector .up.|> LogInstructionCollector
Log4PCollector .up.|> LogInstructionCollector
Log4JCollector ..> LogInstruction
Log4PCollector ..> LogInstruction
LogInstruction "1" o-- "*"Modification
@enduml

@startuml viewControllerNew
package controller {
    class HomeController{
        - search_button_clicked()
        - validate_date_range()
        - update_branch_list(repo_name : String)
        - new_repo_button_clicked()
        - delete_repo_button_clicked()
    }
    class TraceVisualizerController{
        - set_strategy_collector(strategy : String) : LogInstructionCollectorsStrategy
        - set_strategy_generator_file(strategy : String) : LogInstructionFileGeneratorsStrategy
    }
}

package view {
    class CommitWindowView{
        - code_table : QTableWidget
    }

    class HomeView {
        - new_repo : QLineEdit
        - select_folder : QPushButton
        - clone_button : QPushButton
        - branches : QComboBox
        - repo_list : QComboBox
        - new_repo_button : QPushButton
        - delete_repo_button : QPushButton
        - searched_path : QLineEdit
        - searched_author : QLineEdit
        - slected_framework : QListWidget
        - from_date_label : QLabel
        - from_calendar : QCalendarWidget
        - to_date_label : QLabel
        - to_calendat : QCalendarWidget
        - search_button : QPushButton
        + setRepos(repos : List<String>)
        + setBranches(branches : List<String>)
    }
    class TraceVisualizerView{
        - log_instructions_list : QListWidget
        - graphic : QGraphicsView
        + set_log_instructions(logInstructions : List<LogInstruction>)
        + set_graphic(graphic : QGraphicsView)
    }
}

HomeController "1" o-- "1" HomeView
HomeController ..> TraceVisualizerController
HomeController ..> NewRepoController

TraceVisualizerController "1" o-- "1" TraceVisualizerView
TraceVisualizerController "1" o-- "1" CommitWindowView
@enduml

@startuml modelControllerNew
package controller {
    class HomeController{
        - search_button_clicked()
        - validate_date_range()
        - update_branch_list(repo_name : String)
        - new_repo_button_clicked()
        - delete_repo_button_clicked()
    }
    class TraceVisualizerController{
        - set_strategy_collector(strategy : String) : LogInstructionCollectorsStrategy
        - set_strategy_generator_file(strategy : String) : LogInstructionFileGeneratorsStrategy
    }

    class NewRepoController{
        - ok_button_clicked()
        - cancel_button_clicked()
    }
}

package model {
    package GraphBuilders{
        
        class GraphBuilder{
            + build_graph(path_to_file : String) : QGraphicsView
        }
    }
    package LogInstructionCollectors{
        interface LogInstructionCollector{
            + getLogInstructions():LogInstruction[]
        }
        class Log4JCollector{
            + getLogInstructions():LogInstruction[]
        }
        class Log4PCollector{
            + getLogInstructions():LogInstruction[]
        }

        class LogInstruction{
            - intruction : String
        }
        class Modification{
            - type : String
            - commit : Commit
        }
    }

    package LogInstructionFileGenerators{
        interface LogInstructionFileGenerator{
            + createFile(logInstructions : List<LogInstruction>) : String
        }

        class CsvFileGenerator implements LogInstructionFileGenerator{
            + createFile(logInstructions : List<LogInstruction>) : String
        }
    }
}
HomeController ..> TraceVisualizerController
HomeController ..> NewRepoController

TraceVisualizerController "1" o-- "1" LogInstructionCollector
TraceVisualizerController "1" o-- "1" LogInstructionFileGenerator
TraceVisualizerController ..> GraphBuilder

Log4JCollector .up.|> LogInstructionCollector
Log4PCollector .up.|> LogInstructionCollector
Log4JCollector ..> LogInstruction
Log4PCollector ..> LogInstruction
LogInstruction "1" o-- "*"Modification
@enduml

@startuml newCohesiveClass
    class LogInstructionDiffGenerator{
        + getCommitChanges(commits : List<Commit>) : List<Modification>
    }
    class ReposManager{
        + get_repos(main_repo_path : String)
        + git_pull(repo_path:String)
        + delete_repo(repo_path:String)
        + getBranches(repo_path : String)
        + clone_repo(repo_url:String, repo_path:String)
    }
@enduml