@startuml component
skinparam component {
  FontSize 13
  BackgroundColor<<library>> Pink
  BackgroundColor<<cache file>> Orange
  BackgroundColor<<code file>> Blue
}



component "desktop application"{
    component "controller" as controller << code file >>
    component "data.csv" as data.csv << cache file >>
    component "LogInstructionFileGenerator" as LogInstructionFileGenerator << code file >>
    component "GraphBuilder" as GraphBuilder << code file >>
    component "LogInstructionGenerator" as LogInstructionGenerator << code file >>
    component "View" as View << code file >>
    component "GitPyhon" as GitPython << library >>
    component "Pyqt6" as Pyqt6 << library >>
    portout " "
}

controller ..> "GraphBuilder"
"GraphBuilder" ..> controller
controller ..> "LogInstructionGenerator"
LogInstructionGenerator ..> controller
controller ..> "LogInstructionFileGenerator"
LogInstructionFileGenerator ..>controller
controller ..> View
View ..> Pyqt6
GraphBuilder ..> Pyqt6
GraphBuilder ..> data.csv
View ..> data.csv
component "GitHub"

GitPython ..> " "
" " ..> GitHub
LogInstructionGenerator ..> GitPython
LogInstructionFileGenerator ..> data.csv

@enduml